# Generated by Django 4.0.4 on 2022-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.TextField(default='Post title', max_length=2000, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
