# Generated by Django 4.0.4 on 2022-05-11 08:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postcomment_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
